
data_set:
  name: imdb_reviews
  schema_file_path: dataset_schema.yaml
  buffer_size: 10000
  batch_size: 64


preprocessing:
  vocab_size: 1000

train_config:
  model_root_dir: model
  model_save_dir: trained_model/saved_model
  model_checkpoint_dir: checkpoint_dir
  epoch: 10
  tensorboard_log_dir: tensor_board_log_dir
  base_accuracy: 0.6
  validation_step: 30


training_pipeline_config:
  artifact_dir: artifacts
